random_forest:
  n_estimators: [100, 200, 300, 500]
  max_depth: [null, 10, 20, 30]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  class_weight: ["balanced"]

logistic_regression:
  C: [0.01, 0.1, 1, 10]
  penalty: ["l2"]
  class_weight: ["balanced"]
  max_iter: [1000]
